name: Descomprimir Portfolio

on:
  push:
    branches:
      - main  # Cambia a "master" si es necesario

jobs:
  unzip-portfolio:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Eliminar archivos antiguos
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'Portfolio.zip' -exec rm -rf {} +

      - name: Descomprimir Portfolio.zip
        run: |
          unzip Portfolio.zip -d ./
          rm Portfolio.zip

      - name: Configurar permisos
        run: git config --global --add safe.directory /github/workspace

      - name: Subir cambios
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/augustobellini/augustobellini.github.io.git
          git add .
          git commit -m "Descomprimir Portfolio"
          git push origin main
