name: Descomprimir y Desplegar

on:
  push:
    branches:
      - main  # Cambia a "master" si tu rama principal tiene ese nombre

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiso explícito para escribir en el repo

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Evita conflictos de credenciales

      - name: Eliminar archivos antiguos (excepto .git, .github y el ZIP)
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'Portfolio.zip' -exec rm -rf {} +

      - name: Descomprimir Portfolio.zip
        run: |
          unzip -o Portfolio.zip -d ./  # -o sobrescribe sin preguntar
          rm -f Portfolio.zip  # Elimina el ZIP tras descomprimir

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Subir cambios al repositorio
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticación
        run: |
          git add .
          git commit -m "🚀 Deploy automático: Sitio actualizado"
          git push origin HEAD:main
