name: Descomprimir Portfolio

on:
  push:
    branches:
      - main

jobs:
  unzip-portfolio:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Da permisos de escritura al token

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # Importante para autenticación
          fetch-depth: 0

      - name: Eliminar archivos antiguos
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'Portfolio.zip' -exec rm -rf {} +

      - name: Descomprimir Portfolio.zip
        run: |
          unzip Portfolio.zip -d ./
          rm Portfolio.zip

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Subir cambios
        run: |
          git add .
          git commit -m "Descomprimir Portfolio"
          git push origin HEAD:main
