name: Desplegar Portfolio

on:
  push:
    branches:
      - main  # Cambia a "master" si es necesario

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Permiso clave para escribir

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Eliminar archivos antiguos
        run: |
          find . -mindepth 1 -maxdepth 1 ! -name '.git' ! -name '.github' ! -name 'Portfolio.zip' -exec rm -rf {} +

      - name: Descomprimir Portfolio.zip
        run: |
          unzip -o Portfolio.zip -d ./
          rm -f Portfolio.zip

      - name: Configurar Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Autenticar y Subir Cambios
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token automático
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/augustobellini/augustobellini.github.io.git
          git add .
          git commit -m "🚀 Sitio actualizado"
          git push origin HEAD:main
